version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: AuthService
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
